# Installation and Mounting

In [1]:
# from google.colab import drive
# drive.mount('/content/drive/')

In [ ]:
!pip install transformers==4.22.2
!pip install sentencepiece

In [4]:
from PIL import Image
import requests
import torch
# from transformers import CLIPProcessor, CLIPModel
import pandas as pd
import numpy as np

In [7]:
k = 6
[i * 5 for i in range(k)] + np.random.choice(5, k)

array([ 1,  7, 11, 15, 22, 27])

# Download Data

In [ ]:
%cd "/content"
# Download MS-COCO-Spanish
!git clone https://github.com/carlosgarciahe/ms-coco-es

# Main

In [2]:
!python3 "/content/drive/MyDrive/Colab Notebooks/GT Limited Supervision/main.py"

python3: can't open file '/content/drive/MyDrive/Colab Notebooks/GT Limited Supervision/main.py': [Errno 2] No such file or directory


# M2M100 - MT Model

## Demo

In [ ]:
from transformers import M2M100Model, M2M100ForConditionalGeneration, M2M100Tokenizer

model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")

Downloading:   0%|          | 0.00/908 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.71M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/272 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14k [00:00<?, ?B/s]

In [ ]:
hi_text = "जीवन एक चॉकलेट बॉक्स की तरह है।"
chinese_text = ["測試進行中。"]

In [ ]:
# translate Hindi to French
tokenizer.src_lang = "hi"
encoded_hi = tokenizer(hi_text, return_tensors="pt")
generated_tokens = model.generate(**encoded_hi, forced_bos_token_id=tokenizer.get_lang_id("fr"))
tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

['La vie est comme une boîte de chocolat.']

In [ ]:
# translate Chinese to English
tokenizer.src_lang = "zh"
encoded_zh = tokenizer(chinese_text, return_tensors="pt")
generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
out = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
out

/usr/local/lib/python3.7/dist-packages/transformers/generation_utils.py:1232: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 200 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  UserWarning,


['Testing is ongoing.']

In [ ]:
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M", src_lang="en", tgt_lang="fr")

src_text = "Life is like a box of chocolates."
tgt_text = "La vie est comme une boîte de chocolat."

model_inputs = tokenizer(src_text, text_target=tgt_text, return_tensors="pt")
loss = model(**model_inputs)  # forward pass

In [ ]:
# loss.encoder_last_hidden_state.shape
loss.encoder_last_hidden_state

tensor([[[-1.2714,  1.9093,  0.7436,  ...,  0.2802,  0.8649,  1.1141],
         [-1.3060, -0.5871, -0.4232,  ...,  0.3074, -0.1359,  1.9508],
         [ 1.8242, -0.5292,  1.2162,  ...,  0.8727, -2.8189,  0.8455],
         ...,
         [-1.3904, -1.4817, -0.1465,  ...,  0.4703, -0.5209,  0.5213],
         [ 0.2411,  0.8767,  0.8628,  ...,  0.3715, -0.7093,  0.5579],
         [ 0.0457,  0.0600, -0.0096,  ...,  0.0141,  0.0106, -0.0316]]],
       grad_fn=<NativeLayerNormBackward0>)

## Baseline: Translating Spanish into English

### N = 10

In [ ]:
!python3 "main_MT.py"

Streaming output truncated to the last 5000 lines.
[998 / 1998]: image_name: 14998
Rank of Correct Image: 1 / 5

original text:  Un niño con camiseta amarilla y pantalones cortos azules jugando al tenis.
translated text:  A child with yellow shirt and blue short pants playing tennis.
[999 / 1998]: image_name: 15002
Rank of Correct Image: 1 / 5

original text:  Un baño con grafitis pintados por las paredes.
translated text:  A bathroom with graphite painted by the walls.
[1000 / 1998]: image_name: 15006
Rank of Correct Image: 2 / 5

original text:  Un perro con una tiara y su cabeza apoyada en los reposabrazos.
translated text:  A dog with a tiara and his head supported in the shells.
[1001 / 1998]: image_name: 15008
Rank of Correct Image: 1 / 5

original text:  Una mujer saltando mientras golpea una pelota de tenis.
translated text:  A woman jumping while hit a tennis ball.
[1002 / 1998]: image_name: 15011
Rank of Correct Image: 1 / 5

original text:  Un pájaro planeando con las alas e

### N = 50

In [ ]:
!python3 "main_MT.py"

Streaming output truncated to the last 5000 lines.
[998 / 1998]: image_name: 14998
Rank of Correct Image: None / 5

original text:  Un niño con camiseta amarilla y pantalones cortos azules jugando al tenis.
translated text:  A child with yellow shirt and blue short pants playing tennis.
[999 / 1998]: image_name: 15002
Rank of Correct Image: 1 / 5

original text:  Un baño con dos váteres y grafitis en las paredes.
translated text:  A bathroom with two vats and graphite on the walls.
[1000 / 1998]: image_name: 15006
Rank of Correct Image: 2 / 5

original text:  Un perro acostado en un sofá con una corona.
translated text:  A dog lying on a sofa with a crown.
[1001 / 1998]: image_name: 15008
Rank of Correct Image: 1 / 5

original text:  Una mujer balanceando una raqueta de tenis en una pista.
translated text:  A woman balancing a tennis racket on a track.
[1002 / 1998]: image_name: 15011
Rank of Correct Image: 1 / 5

original text:  Un pájaro blanco y negro volando a través de un cielo az

### N = 100

In [ ]:
!python3 "main_MT.py"

Streaming output truncated to the last 5000 lines.
[998 / 1998]: image_name: 14998
Rank of Correct Image: 2 / 5

original text:  Un niño pequeño con la postura lista para golpear con su raqueta de tenis.
translated text:  A little boy with the posture ready to hit with his tennis racket.
[999 / 1998]: image_name: 15002
Rank of Correct Image: 1 / 5

original text:  Una gran cantidad de grafitis en las paredes de un baño.
translated text:  A lot of graphite on the walls of a bathroom.
[1000 / 1998]: image_name: 15006
Rank of Correct Image: 1 / 5

original text:  Un perro con una tiara y su cabeza apoyada en los reposabrazos.
translated text:  A dog with a tiara and his head supported in the shells.
[1001 / 1998]: image_name: 15008
Rank of Correct Image: 1 / 5

original text:  Una jugadora de tenis saltando en el aire para devolver una pelota.
translated text:  A tennis player jumping in the air to return a ball.
[1002 / 1998]: image_name: 15011
Rank of Correct Image: 4 / 5

original text

### N = 150

In [ ]:
!python3 "main_MT.py"

Streaming output truncated to the last 5000 lines.
[998 / 1998]: image_name: 14998
Rank of Correct Image: 2 / 5

original text:  Un joven en pantalones cortos azules jugando al tenis.
translated text:  A young man in blue short pants playing tennis.
[999 / 1998]: image_name: 15002
Rank of Correct Image: 2 / 5

original text:  Una gran cantidad de grafitis en las paredes de un baño.
translated text:  A lot of graphite on the walls of a bathroom.
[1000 / 1998]: image_name: 15006
Rank of Correct Image: 1 / 5

original text:  Un perro marrón y blanco con una corona.
translated text:  A brown and white dog with a crown.
[1001 / 1998]: image_name: 15008
Rank of Correct Image: 1 / 5

original text:  Una jugadora de tenis saltando en el aire para devolver una pelota.
translated text:  A tennis player jumping in the air to return a ball.
[1002 / 1998]: image_name: 15011
Rank of Correct Image: 2 / 5

original text:  Un pájaro blanco y negro volando a través de un cielo azul.
translated text:  A 

# FreddeFrallan/Multilingual-CLIP

## Download the pretrained model

In [ ]:
!pip install multilingual-clip torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Demo

In [ ]:
from multilingual_clip import pt_multilingual_clip
import transformers

texts = [
    'Three blind horses listening to Mozart.',
    'Älgen är skogens konung!',
    'Wie leben Eisbären in der Antarktis?',
    'Вы знали, что все белые медведи левши?'
]
model_name = 'M-CLIP/XLM-Roberta-Large-Vit-L-14'

# Load Model & Tokenizer
model = pt_multilingual_clip.MultilingualCLIP.from_pretrained(model_name)
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)

tokenizer = tokenizer
embeddings = model.forward(texts, tokenizer)
print(embeddings.shape)

Downloading:   0%|          | 0.00/188 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/616 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.decoder.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

torch.Size([4, 768])


In [ ]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

CLIPmodel = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
CLIPprocessor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


In [ ]:
device = device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CLIPmodel = CLIPmodel.to(device)
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = CLIPprocessor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)
inputs = inputs.to(device)
outputs = CLIPmodel(**inputs)
logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

In [ ]:
probs

tensor([[0.9949, 0.0051]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [ ]:
inputs

{'input_ids': tensor([[49406,   320,  1125,   539,   320,  2368, 49407],
        [49406,   320,  1125,   539,   320,  1929, 49407]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]], device='cuda:0'), 'pixel_values': tensor([[[[ 0.5873,  0.5873,  0.6165,  ...,  0.0617,  0.0471, -0.0259],
          [ 0.5727,  0.5727,  0.6603,  ...,  0.1201,  0.0763,  0.0909],
          [ 0.5873,  0.5435,  0.6165,  ...,  0.0325,  0.1201,  0.0617],
          ...,
          [ 1.8719,  1.8573,  1.8719,  ...,  1.3902,  1.4340,  1.4194],
          [ 1.8281,  1.8719,  1.8427,  ...,  1.4486,  1.4340,  1.5070],
          [ 1.8573,  1.9011,  1.8281,  ...,  1.3756,  1.3610,  1.4486]],

         [[-1.3169, -1.3019, -1.3169,  ..., -1.4970, -1.4369, -1.4820],
          [-1.2418, -1.2718, -1.2268,  ..., -1.4369, -1.4669, -1.4519],
          [-1.2568, -1.3169, -1.2268,  ..., -1.4669, -1.4069, -1.4519],
          ...,
          [ 0.1239,  0.1089,  0.1239,  ..., -0.7016, -